server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pruebatecnica
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    datasource:
      initialization-mode: always
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
